image: node:12.18.4

stages:
  - install
  - test
  - build

install:
  stage: install
  script:
    - npm install
  artifacts:
    expire_in: 1h
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - install
  script:
    - npm run test
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'

build:
  stage: build
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    expire_in: 1h
    paths:
      - dist/
  only:
    - master
